$include[template.ch]
$template[Instructions,
      <!--WIP-->
      <h2>Instructions</h2>
      <ul>
        <li>x86</li>
        <li>CPUID</li>
        <li>MMX</li>
        <li>3DNow!</li>
        <li>SSE</li>
        <li>SSE2</li>
        <li>SSE3</li>
        <li>SSSE3</li>
        <li>SSE4.1</li>
        <li>SSE4.2</li>
        <li>AES-NI</li>
        <li>AVX</li>
        <li>F16C</li>
        <li>XOP</li>
        <li>FMA</li>
        <li>AVX2</li>
        <li>AVX-512</li>
      </ul>]
